title: org-pivotal
description: org-pivotal is an Emacs minor mode to extend org-mode with Pivotal Tracker abilities
repository: org-pivotal/org-pivotal
github:
  repository_url: https://github.com/org-pivotal/org-pivotal

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
# plugins:
#   - jekyll-feed
